// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundCloudLite.DAL;

namespace SoundCloudLite.DAL.Migrations
{
    [DbContext(typeof(SoundCloudLiteContext))]
    partial class SoundCloudLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SoundCloudLite.DAL.Entities.ArtistEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Genre");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b875b2df-d265-41a0-b8ea-c47392f741e1"),
                            Country = "Russia",
                            Genre = "Post-hardcore",
                            Name = "Wildways"
                        },
                        new
                        {
                            Id = new Guid("128f2c37-4f7d-4a33-964f-758c8746b087"),
                            Country = "USA",
                            Genre = "Blues-rock",
                            Name = "The Black Keys"
                        });
                });

            modelBuilder.Entity("SoundCloudLite.DAL.Entities.TrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<Guid>("ArtistId");

                    b.Property<string>("EmbeddingHtml");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc82d2d4-fa64-4d63-b003-9de9ee2418b0"),
                            Album = "Day X",
                            ArtistId = new Guid("b875b2df-d265-41a0-b8ea-c47392f741e1"),
                            EmbeddingHtml = "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" allow=\"autoplay\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/419111404&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true\"></iframe>",
                            ReleaseDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sky"
                        },
                        new
                        {
                            Id = new Guid("4f0bb24e-9795-4c95-8291-296269976dfc"),
                            Album = "Day X",
                            ArtistId = new Guid("b875b2df-d265-41a0-b8ea-c47392f741e1"),
                            EmbeddingHtml = "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" allow=\"autoplay\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/419115020&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true\"></iframe>",
                            ReleaseDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lost"
                        },
                        new
                        {
                            Id = new Guid("f395018f-4e08-460f-948d-47076fa15792"),
                            Album = "El Camino",
                            ArtistId = new Guid("128f2c37-4f7d-4a33-964f-758c8746b087"),
                            EmbeddingHtml = "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" allow=\"autoplay\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/28177029&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true\"></iframe>",
                            ReleaseDate = new DateTime(2011, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Run Right Back"
                        },
                        new
                        {
                            Id = new Guid("206a36a3-44e3-44db-ab75-3909306b7bda"),
                            Album = "Turn Blue",
                            ArtistId = new Guid("128f2c37-4f7d-4a33-964f-758c8746b087"),
                            EmbeddingHtml = "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" allow=\"autoplay\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/255881185&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true\"></iframe>",
                            ReleaseDate = new DateTime(2015, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "In Time"
                        },
                        new
                        {
                            Id = new Guid("de260092-b0a3-447a-b50c-b2cee90e5a15"),
                            Album = "Lo/Hi",
                            ArtistId = new Guid("128f2c37-4f7d-4a33-964f-758c8746b087"),
                            EmbeddingHtml = "<iframe width=\"100%\" height=\"300\" scrolling=\"no\" frameborder=\"no\" allow=\"autoplay\" src=\"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/584680629&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true\"></iframe>",
                            ReleaseDate = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lo/Hi"
                        });
                });

            modelBuilder.Entity("SoundCloudLite.DAL.Entities.TrackEntity", b =>
                {
                    b.HasOne("SoundCloudLite.DAL.Entities.ArtistEntity", "Artist")
                        .WithMany("TrackList")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
